package org.quilombo.audioscape;

public enum AudioScapeStates {

    INITIALIZING,
    CHOOSING_RANDOM_VIDEO,
    SHOWING_VIDEO,
    SHOWING_INSTRUCTIONS,
    ATTENTION,
    RECORDING,
    PROCESSING,
    SHOWING_RESULT,
    APPROVE,
    APPROVE_YES,
    APPROVE_NO,
    CLEANUP_ON_ERROR
}
